-- Дроп таблиц для новых тестов
DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS films_directors;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS directors;
--

CREATE TABLE IF NOT EXISTS ratings(
rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
rating_name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS films(
film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
rating_id INTEGER REFERENCES ratings (rating_id),
name VARCHAR NOT NULL,
description VARCHAR(200),
release_date DATE CHECK release_date > '1895-12-28' NOT NULL,
duration INTEGER CHECK duration > 0
);

CREATE TABLE IF NOT EXISTS genres(
genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
genre_name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres(
film_id INTEGER REFERENCES films (film_id),
genre_id INTEGER REFERENCES genres (genre_id),
PRIMARY KEY(film_id,genre_id)
);

CREATE TABLE IF NOT EXISTS users(
user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email VARCHAR NOT NULL UNIQUE,
login VARCHAR NOT NULL UNIQUE,
name VARCHAR,
birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS likes(
film_id INTEGER REFERENCES films (film_id),
user_id INTEGER REFERENCES users (user_id),
PRIMARY KEY(film_id,user_id)
);

CREATE TABLE IF NOT EXISTS friends(
user_id INTEGER REFERENCES users (user_id) ,
friend_id INTEGER REFERENCES users (user_id),
status boolean DEFAULT FALSE NOT NULL
);

--Новые таблицы
--Режесёры
CREATE TABLE IF NOT EXISTS directors(
director_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
director_name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS films_directors(
film_id INTEGER REFERENCES films (film_id),
director_id INTEGER REFERENCES directors (director_id),
PRIMARY KEY(film_id, director_id)
);